CREATE TABLE users ( 
    id SERIAL PRIMARY KEY, 
    user_id VARCHAR(50) NOT NULL UNIQUE, 
    password VARCHAR(255) NOT NULL, 
    nick_name VARCHAR(50) NOT NULL, 
    status VARCHAR(20) DEFAULT 'DEFAULT', 
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    is_admin BOOLEAN DEFAULT FALSE, 
    is_withdraw BOOLEAN DEFAULT FALSE );